# 1. إعدادات قاعدة البيانات (MongoDB)
spring.data.mongodb.uri=mongodb+srv://youssefmn22:youssefmn22@cluster0.goez5fk.mongodb.net/moviesDB?retryWrites=true&w=majority
spring.data.mongodb.database=moviesDB
spring.data.mongodb.auto-index-creation=true

# 2. إعدادات السيرفر والبورت
server.port=5000

# 3. مفتاح TMDB السري (API Key)
# حط المفتاح اللي جبته هنا مكان النقط
tmdb.api.key=480fd49f76a6c9ada2b91fc2297c6af7

# 4. إعدادات اللوج (Logging)
logging.level.root=INFO